# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0f21c62a1650ef8e702ea1a37c776cb4"
name = "custom-app-check"
application_url = "https://incident-margaret-mattress-je.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "learn-theme-build.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_inventory,read_product_listings,read_products,write_content,write_discounts,write_products,write_customers"

[auth]
redirect_urls = [
  "https://incident-margaret-mattress-je.trycloudflare.com/auth/callback",
  "https://incident-margaret-mattress-je.trycloudflare.com/auth/shopify/callback",
  "https://incident-margaret-mattress-je.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
